; Xdebug 3
xdebug.mode=debug,develop
xdebug.start_with_request=trigger
xdebug.client_port=9003
xdebug.idekey=PHPSTORM

; Docker → conectar del contenedor al host (IDE)
xdebug.discover_client_host=0
xdebug.client_host=host.docker.internal

; (opcional) logs para diagnosticar
; xdebug.log=/tmp/xdebug.log
; xdebug.log_level=7
