services:

  db:
    image: mariadb:11.8.5-noble
    container_name: "${ENVIROMENT}-mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "${ENVIROMENT}-phpmyadmin"
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

  php:
    build:
      context: .
      dockerfile: Dockerfile.drupal
    container_name: "${ENVIROMENT}-php"
    env_file:
      - .env
    volumes:
      - './src:/var/www/html'
      - './conf/php/.bashrc:/root/.bashrc'
      - './conf/php/php-drupal.ini:/usr/local/etc/php/php.ini'
      - './conf/php/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini:ro'
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    container_name: "${ENVIROMENT}-nginx"
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - './src:/var/www/html'
      - './logs/nginx:/var/log/nginx'
      - './conf/nginx-drupal:/etc/nginx/conf.d'
    depends_on:
      - php

  varnish:
    image: varnish:fresh
    container_name: "${ENVIROMENT}-varnish"
    restart: always
    ports:
      - "${VARNISH_PORT}:80"
    volumes:
      - ./logs/varnish:/var/log/
      - ./conf/varnish-drupal/varnish.vcl:/etc/varnish/default.vcl:ro
    environment:
      BACKENDS: "nginx"
      BACKENDS_PORT: 80
      BACKENDS_PROBE_ENABLED: "false"
    logging:
      options:
        max-size: 10m
